# Generated by Django 6.1.1 on 2026-09-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='accounts.hospitalprofile'),
        ),
    ]
