# Generated by Django 6.1.1 on 2026-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bloodrequest_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Broadcasted', 'Broadcasted'), ('Coordinating', 'Coordinating'), ('Fulfilled', 'Fulfilled'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
