# Generated by Django 6.1.1 on 2026-09-26 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('requester', 'Requester'), ('donor', 'Donor'), ('hospital', 'Hospital Staff'), ('blood_bank', 'Blood Bank Staff')], default='requester', max_length=20),
        ),
        migrations.CreateModel(
            name='BloodBankProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_bank_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
