# Generated by Django 6.1.1 on 2026-09-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role_bloodbankprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorresponse',
            old_name='responded_at',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='donorresponse',
            unique_together={('donor', 'blood_request')},
        ),
        migrations.RemoveField(
            model_name='requestverification',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='response',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Accepted', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Verification Pending', 'Verification Pending'), ('Verified', 'Verified'), ('Broadcasted', 'Broadcasted'), ('Coordinating', 'Coordinating'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donorresponse',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.donorprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('General', 'General'), ('Blood Request', 'Blood Request'), ('Emergency', 'Emergency'), ('Donor Response', 'Donor Response')], default='General', max_length=30),
        ),
        migrations.AlterField(
            model_name='requestverification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='status',
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accounts.bloodbankprofile')),
            ],
            options={
                'unique_together': {('blood_bank', 'blood_group')},
            },
        ),
    ]
